Use config file for prebuild commands

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,11 +1,22 @@
 #!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env-dir>
 
-BUILD_DIR=$1
-CACHE_DIR=$2
-ENV_DIR=$3
-BUILDPACK_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)
+### Configure environment
 
-source "$BUILDPACK_DIR/lib/output.sh"
+set -o errexit    # always exit on error
+set -o pipefail   # don't ignore exit codes when piping output
+unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
+
+### Configure directories
+
+BUILD_DIR=${1:-}
+CACHE_DIR=${2:-}
+ENV_DIR=${3:-}
+BP_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)
+
+source "$BP_DIR/lib/output.sh"
+
+build_start_time=$(nowms)
 
 if [ ! -f "$ENV_DIR/APP_ROOT" ]; then
   error "APP_ROOT not set. Aborting."
@@ -22,10 +33,10 @@ fi
 
 cd $BUILD_DIR
 
-header "build @kvittoapp/api-client"
-yarn workspace @kvittoapp/api-client run build
-header "build @kvittoapp/ducks"
-yarn workspace @kvittoapp/ducks run build
+if [ -f "$BUILD_DIR/.workspaces-prebuild" ]; then
+  while read in; do yarn workspace "$in"; done < "$BUILD_DIR/.workspaces-prebuild"
+fi
+
 header "build ${APP_NAME}"
 yarn workspace $APP_NAME run build
 
